---
- name: checking existence of per-user basic scripts to start vnc
  stat:
    path: "/home/{{ item.username }}/vncstart.sh"
  register: checkvncstart
  with_items: "{{ vnc_users }}"

- name: Update per-user basic scripts to start vnc
  template:
    src: vncstart.sh.j2
    dest: "/home/{{ item.item.username }}/vncstart.sh"
    mode: 0755
    owner: "{{ item.item.username }}"
    group: "{{ item.item.usergroup | default(item.item.username) }}"
  when:
    - vnc_ansible_managed_startup_scripts or not item.stat.exists
  with_items: "{{ checkvncstart.results }}"

- name: checking existence of per-user basic scripts to stop vnc
  stat:
    path: "/home/{{ item.username }}/vncstop.sh"
  register: checkvncstop
  with_items: "{{ vnc_users }}"

- name: Update per-user basic scripts to stop vnc
  template:
    src: vncstop.sh.j2
    dest: "/home/{{ item.item.username }}/vncstop.sh"
    mode: 0755
    owner: "{{ item.item.username }}"
    group: "{{ item.item.usergroup | default(item.item.username) }}"
  when:
    - vnc_ansible_managed_startup_scripts or not item.stat.exists
  with_items: "{{ checkvncstop.results }}"

#Nautilus error. Unable to create a required folder.
- name: create .config directories.
  file:
    path: "/home/{{ item.username }}/.config"
    state: directory
    mode: 0700
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
  with_items: "{{ vnc_users }}"

- name: add vncstart.sh to .bashrc for each user 
  lineinfile:
    path: "/home/{{ item.username }}/.bashrc"
    line: /home/{{ item.username }}/vncstart.sh 2> /dev/null
  when:
    - vnc_bashrc_startup 
  with_items: "{{ vnc_users }}"

- name: start vnc for each user
  shell: su -c '/home/{{ item.username }}/vncstart.sh' {{ item.username }} # noqa 301 305
  with_items: "{{ vnc_users }}"
  ignore_errors: yes
